//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuthSystemApi.Services.EmailTemplate {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Templates {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Templates() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AuthSystemApi.Services.EmailTemplate.Templates", typeof(Templates).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///&lt;body style=&quot;font-family: Arial, sans-serif; line-height: 1.6; color: #333;&quot;&gt;
        ///    &lt;div style=&quot;max-width: 600px; margin: 0 auto; padding: 20px;&quot;&gt;
        ///        &lt;h2 style=&quot;color: #2c3e50; border-bottom: 2px solid #3498db; padding-bottom: 10px;&quot;&gt;
        ///            New Job Application Received
        ///        &lt;/h2&gt;
        ///        
        ///        &lt;div style=&quot;background-color: #f8f9fa; padding: 20px; border-radius: 5px; margin: 20px 0;&quot;&gt;
        ///            &lt;h3 style=&quot;color: #2c3e50; margin-top: 0;&quot;&gt;Job Details&lt;/h3&gt;
        ///            &lt;p&gt;&lt;strong [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JobApplicationNotification {
            get {
                return ResourceManager.GetString("JobApplicationNotification", resourceCulture);
            }
        }
    }
}
